name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: felipefx1510
          outputs: dist/github-contribution-grid-snake.svg
          # OUTPUT_PATH: dist/github-contribution-grid-snake.svg
          # Você pode adicionar ou modificar as cores aqui, se desejar
          # COLOR_HEAD: '#...'
          # COLOR_TAIL_1: '#...'
          # COLOR_TAIL_2: '#...'
          # COLOR_BODY: '#...'
          # COLOR_SNAKE: '#...'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualiza a animação da cobrinha de contribuições"
          file_pattern: dist/github-contribution-grid-snake.svg